language: node_js
node_js:
  - node
cache: yarn
script:
  - yarn lint
  - yarn test
  - yarn build:prod
deploy:
  provider: pages
  local-dir: dist
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
