version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:11.9
    steps:
      - checkout

      - run:
          name: Checkout submodules
          command: git submodule update --init

      - restore_cache:
          key: yarn_lock-{{ checksum "yarn.lock" }}

      - run:
          name: Install Node dependencies
          command: yarn --frozen-lockfile

      - save_cache:
          key: yarn_lock-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - ./node_modules

      - run:
          name: Lint source code
          command: yarn lint

      - run:
          name: Run unit tests
          command: |
            yarn test --reporter xunit --reporter-options output=reports/mocha/test-results.xml

      - store_test_results:
          path: ./reports
      - store_artifacts:
          path: ./reports
          destination: tests/

      - run:
          name: Build client package
          command: |
            rm -rf dist # Clean the output directory before building
            yarn build:prod

      - deploy:
          name: Deploy client assets to GitHub Pages
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              yarn add --pure-lockfile --silent gh-pages
              git config user.email "deploy@circleci.com"
              git config user.name "circleci"
              yarn gh-pages --message "[skip ci] Deploy" --dist dist/
            fi

      - store_artifacts:
          path: dist
          destination: dist
