name: Continuous Integration
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Checkout submodules
        run: git submodule update --init

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache node modules
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Node dependencies
        run: yarn install --frozen-lockfile

      - name: Lint source code
        run: yarn lint

      - name: Run unit tests
        run: yarn test --reporter xunit --reporter-options output=reports/mocha/test-results.xml

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: reports/mocha/test-results.xml

      - name: Build client package
        run: |
          rm -rf dist # Clean the output directory before building
          yarn build:prod

      - name: Upload build output
        uses: actions/upload-artifact@v2
        with:
          name: distributable
          path: dist/

      # - deploy:
      #     name: Deploy client assets to GitHub Pages
      #     command: |
      #       if [ "${CIRCLE_BRANCH}" == "master" ]; then
      #         yarn add --pure-lockfile --silent gh-pages
      #         git config user.email "deploy@circleci.com"
      #         git config user.name "circleci"
      #         yarn gh-pages --message "[skip ci] Deploy" --dist dist/
      #       fi
